name: Generate Snake Animation

on:
  # हर 24 घंटे में ऑटोमैटिक चलेगा
  schedule:
    - cron: "0 0 * * *"
  
  # मैन्युअल चलाने के लिए
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Snake animation SVG जनरेट करके सीधे output ब्रांच में पुश करना (No extra action needed)
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
